### PR TITLE
Release 2 0

### PR DESCRIPTION
**Pull request by christianwiedemann**

### CODE REVIEW

**Comment by joelpittet** [comment]
Anything I can do to help this PR along @christianwiedemann ? There are many dependencies in wingsuit

And some have some critical security issues:
```
$ yarn audit
126 vulnerabilities found - Packages audited: 3920
Severity: 22 Low | 31 Moderate | 64 High | 9 Critical
Done in 6.03s.
```

My motivation to help move this PR

**Comment by Maarten-1984** [comment]
Is this update still on the roadmap? I'd like to make use of wingsuit-designsystem, but it's current version is a bit too outdated.

**Comment by christianwiedemann** [comment]
Hi, I am currently working on this upgrade. Hope I can release a first beta with storybook 7 and webpack 5 support end of next month.

**Comment by Maarten-1984** [comment]
@christianwiedemann any updates on the status of this pr? Launching 2.0 anytime soon? ^^

**Comment by christianwiedemann** [comment]
Hi, I am nearly ready with the first rc. It works with storybook 8 and the migration path should be not smooth? (In my test it is. hopefully). I looking for some guys who want to test it in their projects. Thanks!

**Comment by joelpittet** [comment]
This branch isn’t merged into master yet and is currently 55 commits behind. I’ve been using 2.x for a while, and it seems stable overall. However, updating the dependencies is challenging due to the high number of them. 

@christianwiedemann , what can we do to get this across the finish line?

**Pull request closed without merging**
